sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# Note: Disabled pypy3 due to currently being broken on travis-ci.
# See: https://github.com/travis-ci/travis-ci/issues/6277#issuecomment-265128578
#  - "pypy3"
matrix:
  include:
    - python: "2.7"
      env: TOXENV=perf

before_install: |
  pip install tox virtualenv
  if [ ! -v TOXENV ]
  then
    __py_ver=$TRAVIS_PYTHON_VERSION
    __tox_dfl=${__py_ver/[0-9].[0-9]/py${__py_ver/.}}
    export TOXENV=${TOXENV:-$__tox_dfl}
  fi
  function announce()
    { echo -e "$ANSI_GREEN$@${ANSI_RESET}"; }
  function tox()
    { announce "Running tox in TOXENV=$TOXENV"; env tox "$@"; }

install: tox --notest
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip

deploy:
  provider: pypi
  distributions: 'sdist bdist_wheel'
  on:
    branch: 'master'
    tags: true
  password:
    secure: >-
      Yg5m1M3mhezSOdEA2bfQ/0tU4T5/kh9DjH11lvNVZA7QSY4AWp0Ri
      38Ea5bk7HP24nlFAXFTrrWr5UJ2ZjdJ/P04tFIWA4yP1H+HU9IF8/
      3FSauKjT2uzd0Cy7aP3PB5k2RFNPdtmHqCJr9o5yjAgT74Pv/dM5k
      t8Qj3h5szdpI=
  user: 'pytest-catchlog-ci'
